tailwind.config.js
change the font size measurements to relative and rename the font variables
=> change font from tailwind

src/app/register/page.jsx, src/components/Form.jsx
* created form component
* created view register
* login view changes
=> created form component

src/common/Icons.jsx, src/common/TableRow.jsx
=> add actions prop in main label and add icon that was delete

src/common/HorizontalSection.jsx, src/common/Icons.jsx
-Hice un common de una row que se utiliza dentro de varias tables, agregando props para adecuar su uso.
=> common finished to add in table component and add icon in Icons.jsx

src/app/home/my-team/data/page.jsx, src/app/home/my-team/page.jsx, src/components/Card.jsx
-> Cree la vista de "My Team" sin data
-> Modifique el componente Card. Acomde el children que recibe por props para que se muestre mejor y con mayor "flexibilidad"
=> setting view My Team with NO data and fixed Card component on children

src/app/home/my-team/data/page.jsx, src/common/TeamCard.jsx, src/components/ColaboratorCard.jsx, src/components/FitlerModal.jsx, src/components/TableTeam.jsx
- Cree el componente FilterModal para poder reutilizar el modal de un filtro.
- Cree la tabla "TableTeam"  en components
- Modifique la vista de  My Team agregandole un estado para el manejo de las vistas del team, si es grid o table.
=> setting table display and filter modal, on my team view

src/components/TableDetails.jsx
- Desarrollo de row con data para aplicarla en el component Table.jsx
=> TableDetails finished for use it in component Table.jsx

src/common/DropdownInput.jsx, src/common/Icons.jsx
- Desarrollé el common de tipo "Select" que trabaja _mediante un array_ que se le pasa por props para que lo tome como opciones del mismo.
- Tengo pendiende la creación de los archivos **JSON** con información para su uso en las distintas pages de la app.
=> input select common finished for use in app through an array

src/common/State.jsx, src/components/Table.jsx, src/components/TableDetails.jsx
- Reformulé la logica de Table.jsx para desplegar las TableDetails cuando se hace click en Dropdown _(hay que hacer una modificacion de su funcionamiento)_
- Agregué la logica de State.jsx en TableDetails.jsx para que tome los estilos dependiendo del **Status** que recibe el objeto.
=> Component Table.jsx finished, add TableDetails into this and i do a minimun modify in State

src/app/home/orders/logistics/page.jsx, src/common/LogisticsRow.jsx, src/components/TableLogistics.jsx
=> create logistics table and add tablen in orders view

.env.example, src/app/api/auth/[...nextauth]/route.js, src/app/login/page.jsx
- Dentro del archivo route.js, se agrego la configuración correspondiente a Azure Provider para el redireccionamiento al login con Microsoft.
=> autentication with azure/microsoft finished. Add information en route.js for sign in with microsoft account in app

src/app/home/addTeam/page.jsx, src/app/user-register/page.jsx
-Se agrego los input correspondiente a las vistas mencionadas **(/AddTeam, /user-register)**
-Estoy desarrollando los Json para _Country/Cities/States_ con la lógica correspondiente para los Inputs. **(Dependiendo el país que elija el cliente, son las ciudades y estados que aparecerán en las opciones del dropdown)**
=> has been add DropDownInput in /AddTeam and /user_register

src/app/home/layout.js, src/app/home/orders/equipment/page.jsx, src/common/EquipmentRow.jsx, src/common/Icons.jsx, src/common/ProductDetail.jsx, src/components/MemberAsideDetails.jsx, src/components/TableEquipment.jsx
=> create aside order id

src/app/home/my-team/data/page.jsx, src/common/SearchInput.jsx, src/common/TeamCard.jsx, src/components/AddMemberForm.jsx, src/components/CreateTeamAside.jsx, src/components/EditTeamsAsideDetails.jsx, src/components/FitlerModal.jsx, src/components/TeamDeatils.jsx, src/components/TeamInfo.jsx, tailwind.config.js
Creacion de componentes para las vistas de asides de:
-> Edit Teams
-> Create Temas
Creacion del componente TeamsDetails:
Creacion del componente TeamInfo:
Creacion de componente AddMemberForm:
=> created asides to edit and create teams

src/app/home/my-stock/data/page.jsx, src/common/CustomLink.jsx, src/components/RadioButtons.jsx, src/components/Table.jsx, src/components/TableDetails.jsx
=> finish assign to aside

src/app/home/my-team/data/page.jsx, src/components/AddMemberForm.jsx, src/components/CreateTeamAside.jsx
=> createTeamAside finished

src/services/orders.services.js
-Se creo los servicios correspondientes a orders para empezar a consumir data desde Client.
=> feat: create orders services in Client

src/app/home/orders/equipment/page.jsx, src/common/EquipmentRow.jsx, src/common/ProductDetail.jsx, src/components/TableEquipment.jsx, src/services/orders.services.js
-Se realizo los endpoints correspondientes para traer la info de las ordenes y matchear las ordenes con los productos de cada teamMember (tambien se utilizaron funciones para mostrar los status de cada orden y visualizar las fechas).
=> bugfix: finished table with real dates

src/common/DropFilter.tsx, src/common/ShipmentStatus.tsx, src/common/State.tsx, src/common/StatusColors.tsx, src/common/TableRow.tsx, src/models/member.store.ts
- I created StatusColors file to move Colors logic.
- After this modification, State.tsx and TableRow.tsx are more cleaner.
- created FilteredMember in member.store
=> Feat(Client): TODOs in commons

src/app/home/addTeam/page.tsx, src/common/Button.tsx, src/common/Dropdown.tsx, src/common/DropdownInput.tsx, src/common/Icons.tsx, src/components/FormInput.tsx, src/components/Navbar.tsx, src/components/Sidebar.tsx
=> fix(button): buttons fixed and modified some props

src/services/shipment.services.ts, src/services/team.services.ts, src/types/shipment.ts
- Added Shipment.services.ts
- Fixed memeber id type on  delelte member from team service
=> chore (apiServices): created & updated api services

src/app/home/dashboard/page.tsx
=> chore (dashboard): hide notifications

src/app/home/settings/page.tsx, src/components/AccessForm.tsx, src/components/BillingForm.tsx, src/components/CompanyForm.tsx
- Fixed UI
- Hide Payment section (currently unsed)
=> chore (settings): hide unsed section & fixed UI

src/app/home/dashboard/page.tsx, src/common/EmptyDashboardCard.tsx, src/common/index.ts
- Fix Cards of dashboard when then data is empty
- Created a new Common EmptyDashboardCard to solve this
=> fix (dashboard): Cards & shop redirect

package.json, src/app/login/page.tsx, src/common/Button.tsx, src/components/ui/alert-dialog.tsx, src/components/ui/button.tsx
- Added messagge alert to Forgot Password button
https://github.com/firstplug/First-Plug-Platform-Client/assets/90634174/2d7e3e36-7b03-4265-88de-731f048883ae
=> feat (login): added message alert for forgot password

src/app/login/page.tsx, src/app/register/page.tsx, src/common/Input.tsx, src/hooks/useInput.ts
Fixed inputs of login/singUp forms, data validations
=> fix (inputs): fixed set errors from useInputs custom hook

src/common/Input.tsx, src/hooks/useInput.ts
Fixed validations of inputs.
Fixed form: this will be not able to submit if some input has errors
=> fix (input): fixed input & useInput validations

src/app/login/page.tsx
Deleted duplicate `type = "submit"` on login button page
=> fixed duplicate button types

package.json, src/app/login/page.tsx, src/components/LoadAside.tsx, src/services/csv.services.ts, src/types/csv.ts
Added zod validation for load csv files.
=> Feat (zod): adding zod validations

src/app/login/page.tsx, src/components/ui/toast.tsx
Fixed Login UI when user insert Invalid Credentials:
=> fix (login): fixed login error pop alert

src/components/Tables/ProductsTable.tsx
=> chore (tables): new design of stock columns

src/hooks/useInput.ts
fixed validation for special characters at pw validation
=> fix (input): fixed password validations

src/common/EmptyCard.tsx
just add the url to navigate to addProduct when empty product card is rendered
=> on empty product card add link to create product page

src/components/AddProduct/CategoryForm.tsx, src/components/AddProduct/ProductForm.tsx, src/components/AddProduct/ui/GenericAlertDialog.tsx, src/types/product.ts
At this point unique serial number is working fine
=> Fix Location required message

src/components/AddMember/EmployeeData.tsx, src/components/AddMember/JSON/personaldata.json, src/components/AddMember/PersonalData.tsx, src/components/AddProduct/CategoryForm.tsx, src/components/AddProduct/InputProductForm.tsx
disabled position till team is selected or created
startDate allows to select future dates
=> Fix(membercreate):  change rendering dropdowns order

src/components/Alerts/DeleteAction.tsx
validates if user has assigned recoverable products. 
Set message to inform they must reassign products first.
=> feat(member) soft delete member

src/common/AsideTitle.tsx, src/common/ProductDetail.tsx, src/common/SearchInput.tsx, src/components/AddMemberForm.tsx, src/components/Aside.tsx, src/components/AsideContents/AssignProduct.tsx, src/components/CreateTeamAside.tsx, src/components/MemberAsideDetails.tsx, src/components/Tables/Product/ActionButton.tsx, src/components/TeamInfo.tsx, src/models/aside.store.ts, src/models/products.store.ts
Add some other fixes in this same branch such as:
1) Member Aside detail: buttons set at the end of the componente & add overflow in order to scroll products
=> Fix(asideLayout): change with to 50%

src/components/AddMember/JSON/shipmentdata.json
=> fix(member): member zip code = text

src/types/member.ts
change type in zod model
birthDate: z.string().trim().optional(),
updates just fine
=> fix(members): birthDate updates ok

src/common/AsideTitle.tsx, src/components/AddMembersToTeamForm.tsx, src/components/Alerts/AlertProvider.tsx, src/components/Alerts/DeleteAction.tsx, src/components/CreateTeamAside.tsx, src/components/EditTeamsAsideDetails.tsx, src/components/TeamDetails.tsx, src/components/TeamInfo.tsx, src/services/team.services.ts, src/types/alerts.ts, src/types/member.ts
create a crud for teams.
Add the unassign team from member when team is deleted
=> feat(team): CRUD

src/components/AddMembersToTeamForm.tsx
=> fix(team):  Add current team title to edit team aside

src/components/AddProduct/CategoryForm.tsx
Likely a merge in develop overwrote the fixes for the update stock feature, causing it to stop working. This has been resolved.
=> Back to previous fix

src/components/AddProduct/ProductForm.tsx
=> fix(createstock): when selected category is merchandising,

src/components/AddProduct/CategoryForm.tsx
only shows unknown email as selected value but not as a dropdown option
=> Fix(update stock): AssignedMember dropDown: 

src/components/AddMember/MemberForm.tsx, src/components/AddMember/PersonalData.tsx
=> fix: exclude products from member update payload

src/components/Alerts/DeleteAction.tsx, src/models/products.store.ts
=> fix(softDelete): isDeleted: true when deleting a product

src/common/ProductLocation.tsx, src/common/StatusColors.tsx, src/components/Tables/ProductsTable.tsx
center total and available number
change Available bg to green
delivered to purple
=> fix(style): stock product table

src/components/Alerts/AlertProvider.tsx
=> fix(alerts):change alert message for successfully changed

src/components/AddProduct/BulkCreateForm.tsx
- Updated useEffect to correctly detect changes in the location field for products other than the first one.
- Introduced a 200ms delay in the comparison logic to ensure that changes are fully captured before triggering checkbox deselection.
- Adjusted the order of operations to prevent unintended replication of location values across all products when modifying a single product.
=> Fix checkbox deselection issue when modifying location in bulk product creation form

src/components/Tables/Filters/FilterComponent.tsx, src/components/Tables/RootTable.tsx
selected options on top
sort No Data and Not Assigned at the end of the list
=> Filters issues

src/components/AddProduct/CategoryForm.tsx, src/components/AddProduct/DynamicForm.tsx, src/components/AddProduct/ProductForm.tsx, src/components/Tables/Product/ProdcutsDetailsTable.tsx
fix: resolved assignedMember reset issue and model validation logic
- Fixed assignedMember dropdown reverting to "None" after selection.
- Improved model validation to correctly handle "Other" and Product Name requirements.
- Added performance optimizations for form rendering and reactivity.
=> Update other model

src/assets/hooks/useCreateAsset.ts, src/assets/hooks/useUpdateAsset.ts, src/components/LoadAside.tsx, src/components/Tables/MembersTable.tsx, src/members/hooks/useFetchMember.tsx
=> add missing cancel queries in existing hooks and

src/app/home/dashboard/page.tsx, src/app/home/my-stock/addOneProduct/page.tsx, src/components/AddProduct/RecoverableSwitch.tsx, src/components/settings/actions/getUserSettings.tsx, src/components/settings/hooks/useFetchUserSettings.tsx
terminal has error fetching recoverable config.
=> Fix: when reload page add product form

src/assets/hooks/usePreFetchAssets.ts, src/components/AddProduct/utils/BulkCreateValidator.tsx, src/models/member.store.ts
=> FIX: apartment doesn't need validation for member

src/members/hooks/useDeleteMember.tsx
=> Fix: delete non recoverable products from deleted

src/components/AddProduct/ProductCondition.tsx
Optimal when there is no other value
=> when is update is true: productCondition value is

src/action-history/components/table/assets/UpdateAssetTable.tsx, src/action-history/components/table/members/UpdateMemberTable.tsx
reset member dropdown when category change
=> Fix: create asset

src/components/AddProduct/ProductForm.tsx
=> Fix required name field when category is other and

src/config/axios.config.ts, src/features/activity/hooks/useActivityTable.ts, src/features/assets/hooks/useAssetsTable.ts, src/features/assets/hooks/useSubtableLogic.tsx, src/features/assigned-users/hooks/useAssignedUsersTable.ts, src/features/auth/hooks/use-auth-v2.ts, src/features/dashboard/components/widgets/computer-updates/computer-updates-table.tsx, src/features/dashboard/components/widgets/latest-activity-widget/latest-activity-table.tsx, src/features/dashboard/components/widgets/upcoming-birthdays/birthday-table.tsx, src/features/fp-tables/components/data-table.tsx, src/features/fp-tables/index.ts, src/features/logistics/hooks/useLogisticsTable.ts, src/features/members/hooks/useMembersTable.ts, src/features/settings/components/profile-settings.tsx, src/features/shipments/hooks/useShipmentsTable.ts, src/features/tenants/hooks/useTenantsSubtableLogic.tsx, src/features/tenants/hooks/useTenantsTable.ts, src/features/unassigned-users/hooks/useUnassignedUsersTable.ts, src/middleware.ts, src/providers/tenant.provider.tsx, src/shared/hooks/useLogisticUser.ts, src/shared/utils/validateAfterAction.ts
=> FIX: validateAfterAction handle async await validateAfterAction
